// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net"

	mock "github.com/stretchr/testify/mock"
)

// NewListener creates a new instance of Listener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewListener(t interface {
	mock.TestingT
	Cleanup(func())
}) *Listener {
	mock := &Listener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Listener is an autogenerated mock type for the Listener type
type Listener struct {
	mock.Mock
}

type Listener_Expecter struct {
	mock *mock.Mock
}

func (_m *Listener) EXPECT() *Listener_Expecter {
	return &Listener_Expecter{mock: &_m.Mock}
}

// Accept provides a mock function for the type Listener
func (_mock *Listener) Accept() (net.Conn, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Accept")
	}

	var r0 net.Conn
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (net.Conn, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() net.Conn); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Conn)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Listener_Accept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Accept'
type Listener_Accept_Call struct {
	*mock.Call
}

// Accept is a helper method to define mock.On call
func (_e *Listener_Expecter) Accept() *Listener_Accept_Call {
	return &Listener_Accept_Call{Call: _e.mock.On("Accept")}
}

func (_c *Listener_Accept_Call) Run(run func()) *Listener_Accept_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Listener_Accept_Call) Return(conn net.Conn, err error) *Listener_Accept_Call {
	_c.Call.Return(conn, err)
	return _c
}

func (_c *Listener_Accept_Call) RunAndReturn(run func() (net.Conn, error)) *Listener_Accept_Call {
	_c.Call.Return(run)
	return _c
}

// Addr provides a mock function for the type Listener
func (_mock *Listener) Addr() net.Addr {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Addr")
	}

	var r0 net.Addr
	if returnFunc, ok := ret.Get(0).(func() net.Addr); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Addr)
		}
	}
	return r0
}

// Listener_Addr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Addr'
type Listener_Addr_Call struct {
	*mock.Call
}

// Addr is a helper method to define mock.On call
func (_e *Listener_Expecter) Addr() *Listener_Addr_Call {
	return &Listener_Addr_Call{Call: _e.mock.On("Addr")}
}

func (_c *Listener_Addr_Call) Run(run func()) *Listener_Addr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Listener_Addr_Call) Return(addr net.Addr) *Listener_Addr_Call {
	_c.Call.Return(addr)
	return _c
}

func (_c *Listener_Addr_Call) RunAndReturn(run func() net.Addr) *Listener_Addr_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type Listener
func (_mock *Listener) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Listener_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Listener_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Listener_Expecter) Close() *Listener_Close_Call {
	return &Listener_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Listener_Close_Call) Run(run func()) *Listener_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Listener_Close_Call) Return(err error) *Listener_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Listener_Close_Call) RunAndReturn(run func() error) *Listener_Close_Call {
	_c.Call.Return(run)
	return _c
}
