platform: "nitro"
proxy:
  port: 8080
measurement: |
  {
    "pcrs": {
      "0": "sKmo596pt4nNwjRQr25VaEj2cNg92FszRBKwX7Y3Ujh6Jkz+O0yXuxRsMrLTWv07",
      "1": "S01bNmGz78EpIJAMgOEm5M54PFIt5sAqKlv3rzorkye4Z3bxiOS+HBxAShKdvaST",
      "2": "ihGnAfFyhtfCaQ5nk+VrftONtmR8mbnFgESk+X3UibFXPQzjw9JZjBDd2KeioKRQ",
      "3": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "4": "qCPabIHXU+nhGcZdNOlh6t6ts85vPpXbEhRxY1f+azLcAvahbgsBN+sKbCfnE+yq",
      "8": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    },
    "module_id": ""
  }
