platform: "sev"

# On Nitro enclave CIDs start from 4, but SEV and TDX start from 3
enclave_cid: "3"
enclave_port: "8080"
enclave_addr: "0.0.0.0:8081"

# On Nitro nonclave CID is always 3, but SEV and TDX is 2
nonclave_cid: "2"
nonclave_port: "8081"
nonclave_addr: "0.0.0.0:8082"
