version: "2"
linters:
  settings:
    tagliatelle:
      case:
        rules:
          json: snake
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
  enable:
    - asciicheck
    - bidichk
    - containedctx
    - contextcheck
    - durationcheck
    - embeddedstructfieldcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - forcetypeassert
    - funcorder
    - gocheckcompilerdirectives
    - gocritic
    - godoclint
    - godox
    - govet
    - iface
    - importas
    - inamedparam
    - ineffassign
    - loggercheck
    - makezero
    - mirror
    - mnd
    - modernize
    - musttag
    - nilnesserr
    - nilnil
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - protogetter
    - reassign
    - recvcheck
    - revive
    - sloglint
    - staticcheck
    - tagalign
    - tagliatelle
    - testifylint
    - thelper
    - unconvert
    - unused
    - wastedassign
    - whitespace
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
