dir: internal/mocks
filename: '{{.InterfaceName}}.go'
structname: '{{.InterfaceName}}'
pkgname: mocks
formatter: goimports
log-level: info
packages:
  github.com/tahardi/bearclave/internal/attestation:
    config:
    interfaces:
      Attester:
      Verifier:
  github.com/tahardi/bearclave/internal/ipc:
    config:
    interfaces:
      IPC:
  io:
    config:
    interfaces:
      ReadCloser:
  net:
    config:
    interfaces:
      Conn:
      Listener:
  net/http:
    config:
    interfaces:
      RoundTripper: