platform: "nitro"
attestations:
  "enclave":
    measurement: |
      {
        "pcrs": {
          "0": "sQJv4+DSSPXsFbVj3yfpCBVwVpDP44OomnrrEv0tSyXEWVLXgO+Eef374HDqRVQm",
          "1": "S01bNmGz78EpIJAMgOEm5M54PFIt5sAqKlv3rzorkye4Z3bxiOS+HBxAShKdvaST",
          "2": "SRszD6wQ/Q7KeR6S6EaWcO99Dbe1xgjX+wY9rc+zA6gt/WoAkdurKfJQGxEZY1Vz",
          "3": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
          "4": "qCPabIHXU+nhGcZdNOlh6t6ts85vPpXbEhRxY1f+azLcAvahbgsBN+sKbCfnE+yq",
          "8": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        },
        "module_id": ""
      }
