platform: "nitro"
proxy:
  port: 8080
measurement: |
  {
    "pcrs": {
      "0": "ualIFzFFxz8IIIqYhij2NxRXw9T62VuFIyvfMCy7RZ25NAXQXTinaP85hwH139JO",
      "1": "S01bNmGz78EpIJAMgOEm5M54PFIt5sAqKlv3rzorkye4Z3bxiOS+HBxAShKdvaST",
      "2": "gF4MerB5+kTOdjdpf/sMMtJDjhXDh47rE5Xep5NZpEXQDp+h82i6nRAXJwvGzF1S",
      "3": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "4": "qCPabIHXU+nhGcZdNOlh6t6ts85vPpXbEhRxY1f+azLcAvahbgsBN+sKbCfnE+yq",
      "8": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    },
    "module_id": ""
  }
