# Here is an example of how you would pass in a custom config
# instead of using the hardcoded defaults in the SDK

# On Nitro enclave CIDs start from 4, but SEV and TDX start from 3
enclave_cid: "4"
enclave_port: "8080"
enclave_addr: "127.0.0.1:8080"

# On Nitro nonclave CID is always 3, but SEV and TDX is 2
nonclave_cid: "3"
nonclave_port: "8081"
nonclave_addr: "127.0.0.1:8081"
