# https://taskfile.dev

version: '3'

vars:
  PROCESS_COMPOSE_PORT: 8081

tasks:
  default:
    cmds:
      - task --list-all
    silent: true

  hello:
    cmds:
      - process-compose up --tui=false --port={{.PROCESS_COMPOSE_PORT}} -f .process-compose.yaml 2> /dev/null
    silent: true