platform: "nitro"
attestations:
  "enclave":
    measurement: |
      {
        "pcrs": {
          "0": "FgYECsWvsZgkyw94PtD5BYPvGsVV3DsLXwDVZOwNIGvXpWym7gSbouA7t9TqiNAL",
          "1": "S01bNmGz78EpIJAMgOEm5M54PFIt5sAqKlv3rzorkye4Z3bxiOS+HBxAShKdvaST",
          "2": "4HQuDkC4V2rq3M/4U55Eg5m5kku5cBdyu10lAdl3V/q6bSqjkOdh72DFpNdFLxAf",
          "3": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
          "4": "qCPabIHXU+nhGcZdNOlh6t6ts85vPpXbEhRxY1f+azLcAvahbgsBN+sKbCfnE+yq",
          "8": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        },
        "module_id": "i-01bdf23ce28366cb5-enc01974a1e041bde39"
      }
ipcs:
  "enclave":
    endpoint: "4:8083"
  "enclave-proxy":
    endpoint: "3:8082"
proxy:
  port: 8080
