platform: "notee"
ipc:
  "enclave":
    send_cid: "3"
    send_port: "8081"
    receive_port: "8082"
  "enclave-proxy":
    send_cid: "4"
    send_port: "8082"
    receive_port: "8081"
proxy:
  port: 8080
