platform: "notee"
attestations:
  "enclave":
    measurement: "Not a TEE platform. Code measurements are not real."
ipcs:
  "enclave":
    endpoint: "127.0.0.1:8083"
  "enclave-proxy":
    endpoint: "127.0.0.1:8082"
proxy:
  port: 8080
