platform: "sev"
ipc:
  "enclave":
    send_cid: "3"
    send_port: "8082"
    receive_port: "8083"
  "enclave-proxy":
    send_cid: "4"
    send_port: "8083"
    receive_port: "8082"
proxy:
  port: 8080
