// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/tahardi/bearclave/internal/attestation"
)

// NewAttester creates a new instance of Attester. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAttester(t interface {
	mock.TestingT
	Cleanup(func())
}) *Attester {
	mock := &Attester{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Attester is an autogenerated mock type for the Attester type
type Attester struct {
	mock.Mock
}

type Attester_Expecter struct {
	mock *mock.Mock
}

func (_m *Attester) EXPECT() *Attester_Expecter {
	return &Attester_Expecter{mock: &_m.Mock}
}

// Attest provides a mock function for the type Attester
func (_mock *Attester) Attest(options ...attestation.AttestOption) (*attestation.AttestResult, error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(options)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Attest")
	}

	var r0 *attestation.AttestResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(...attestation.AttestOption) (*attestation.AttestResult, error)); ok {
		return returnFunc(options...)
	}
	if returnFunc, ok := ret.Get(0).(func(...attestation.AttestOption) *attestation.AttestResult); ok {
		r0 = returnFunc(options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*attestation.AttestResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(...attestation.AttestOption) error); ok {
		r1 = returnFunc(options...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Attester_Attest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Attest'
type Attester_Attest_Call struct {
	*mock.Call
}

// Attest is a helper method to define mock.On call
//   - options
func (_e *Attester_Expecter) Attest(options ...interface{}) *Attester_Attest_Call {
	return &Attester_Attest_Call{Call: _e.mock.On("Attest",
		append([]interface{}{}, options...)...)}
}

func (_c *Attester_Attest_Call) Run(run func(options ...attestation.AttestOption)) *Attester_Attest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[0].([]attestation.AttestOption)
		run(variadicArgs...)
	})
	return _c
}

func (_c *Attester_Attest_Call) Return(attestResult *attestation.AttestResult, err error) *Attester_Attest_Call {
	_c.Call.Return(attestResult, err)
	return _c
}

func (_c *Attester_Attest_Call) RunAndReturn(run func(options ...attestation.AttestOption) (*attestation.AttestResult, error)) *Attester_Attest_Call {
	_c.Call.Return(run)
	return _c
}
