// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewCFSController creates a new instance of CFSController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCFSController(t interface {
	mock.TestingT
	Cleanup(func())
}) *CFSController {
	mock := &CFSController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CFSController is an autogenerated mock type for the CFSController type
type CFSController struct {
	mock.Mock
}

type CFSController_Expecter struct {
	mock *mock.Mock
}

func (_m *CFSController) EXPECT() *CFSController_Expecter {
	return &CFSController_Expecter{mock: &_m.Mock}
}

// MkdirTemp provides a mock function for the type CFSController
func (_mock *CFSController) MkdirTemp(path string, pattern string) (string, error) {
	ret := _mock.Called(path, pattern)

	if len(ret) == 0 {
		panic("no return value specified for MkdirTemp")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return returnFunc(path, pattern)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(path, pattern)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(path, pattern)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CFSController_MkdirTemp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MkdirTemp'
type CFSController_MkdirTemp_Call struct {
	*mock.Call
}

// MkdirTemp is a helper method to define mock.On call
//   - path
//   - pattern
func (_e *CFSController_Expecter) MkdirTemp(path interface{}, pattern interface{}) *CFSController_MkdirTemp_Call {
	return &CFSController_MkdirTemp_Call{Call: _e.mock.On("MkdirTemp", path, pattern)}
}

func (_c *CFSController_MkdirTemp_Call) Run(run func(path string, pattern string)) *CFSController_MkdirTemp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *CFSController_MkdirTemp_Call) Return(name string, err error) *CFSController_MkdirTemp_Call {
	_c.Call.Return(name, err)
	return _c
}

func (_c *CFSController_MkdirTemp_Call) RunAndReturn(run func(path string, pattern string) (string, error)) *CFSController_MkdirTemp_Call {
	_c.Call.Return(run)
	return _c
}

// Path provides a mock function for the type CFSController
func (_mock *CFSController) Path() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Path")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// CFSController_Path_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Path'
type CFSController_Path_Call struct {
	*mock.Call
}

// Path is a helper method to define mock.On call
func (_e *CFSController_Expecter) Path() *CFSController_Path_Call {
	return &CFSController_Path_Call{Call: _e.mock.On("Path")}
}

func (_c *CFSController_Path_Call) Run(run func()) *CFSController_Path_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CFSController_Path_Call) Return(s string) *CFSController_Path_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *CFSController_Path_Call) RunAndReturn(run func() string) *CFSController_Path_Call {
	_c.Call.Return(run)
	return _c
}

// ReadFile provides a mock function for the type CFSController
func (_mock *CFSController) ReadFile(path string) ([]byte, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for ReadFile")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CFSController_ReadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFile'
type CFSController_ReadFile_Call struct {
	*mock.Call
}

// ReadFile is a helper method to define mock.On call
//   - path
func (_e *CFSController_Expecter) ReadFile(path interface{}) *CFSController_ReadFile_Call {
	return &CFSController_ReadFile_Call{Call: _e.mock.On("ReadFile", path)}
}

func (_c *CFSController_ReadFile_Call) Run(run func(path string)) *CFSController_ReadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *CFSController_ReadFile_Call) Return(data []byte, err error) *CFSController_ReadFile_Call {
	_c.Call.Return(data, err)
	return _c
}

func (_c *CFSController_ReadFile_Call) RunAndReturn(run func(path string) ([]byte, error)) *CFSController_ReadFile_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAll provides a mock function for the type CFSController
func (_mock *CFSController) RemoveAll(path string) error {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CFSController_RemoveAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAll'
type CFSController_RemoveAll_Call struct {
	*mock.Call
}

// RemoveAll is a helper method to define mock.On call
//   - path
func (_e *CFSController_Expecter) RemoveAll(path interface{}) *CFSController_RemoveAll_Call {
	return &CFSController_RemoveAll_Call{Call: _e.mock.On("RemoveAll", path)}
}

func (_c *CFSController_RemoveAll_Call) Run(run func(path string)) *CFSController_RemoveAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *CFSController_RemoveAll_Call) Return(err error) *CFSController_RemoveAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CFSController_RemoveAll_Call) RunAndReturn(run func(path string) error) *CFSController_RemoveAll_Call {
	_c.Call.Return(run)
	return _c
}

// WriteFile provides a mock function for the type CFSController
func (_mock *CFSController) WriteFile(path string, data []byte) error {
	ret := _mock.Called(path, data)

	if len(ret) == 0 {
		panic("no return value specified for WriteFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = returnFunc(path, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CFSController_WriteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteFile'
type CFSController_WriteFile_Call struct {
	*mock.Call
}

// WriteFile is a helper method to define mock.On call
//   - path
//   - data
func (_e *CFSController_Expecter) WriteFile(path interface{}, data interface{}) *CFSController_WriteFile_Call {
	return &CFSController_WriteFile_Call{Call: _e.mock.On("WriteFile", path, data)}
}

func (_c *CFSController_WriteFile_Call) Run(run func(path string, data []byte)) *CFSController_WriteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]byte))
	})
	return _c
}

func (_c *CFSController_WriteFile_Call) Return(err error) *CFSController_WriteFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CFSController_WriteFile_Call) RunAndReturn(run func(path string, data []byte) error) *CFSController_WriteFile_Call {
	_c.Call.Return(run)
	return _c
}
