// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewIOController creates a new instance of IOController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIOController(t interface {
	mock.TestingT
	Cleanup(func())
}) *IOController {
	mock := &IOController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IOController is an autogenerated mock type for the IOController type
type IOController struct {
	mock.Mock
}

type IOController_Expecter struct {
	mock *mock.Mock
}

func (_m *IOController) EXPECT() *IOController_Expecter {
	return &IOController_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type IOController
func (_mock *IOController) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IOController_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type IOController_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *IOController_Expecter) Close() *IOController_Close_Call {
	return &IOController_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *IOController_Close_Call) Run(run func()) *IOController_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IOController_Close_Call) Return(err error) *IOController_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *IOController_Close_Call) RunAndReturn(run func() error) *IOController_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function for the type IOController
func (_mock *IOController) Send(request []byte) ([]byte, error) {
	ret := _mock.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) ([]byte, error)); ok {
		return returnFunc(request)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = returnFunc(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IOController_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type IOController_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - request
func (_e *IOController_Expecter) Send(request interface{}) *IOController_Send_Call {
	return &IOController_Send_Call{Call: _e.mock.On("Send", request)}
}

func (_c *IOController_Send_Call) Run(run func(request []byte)) *IOController_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *IOController_Send_Call) Return(response []byte, err error) *IOController_Send_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *IOController_Send_Call) RunAndReturn(run func(request []byte) ([]byte, error)) *IOController_Send_Call {
	_c.Call.Return(run)
	return _c
}
