// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/tahardi/bearclave/internal/drivers"
)

// NewNSM creates a new instance of NSM. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNSM(t interface {
	mock.TestingT
	Cleanup(func())
}) *NSM {
	mock := &NSM{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// NSM is an autogenerated mock type for the NSM type
type NSM struct {
	mock.Mock
}

type NSM_Expecter struct {
	mock *mock.Mock
}

func (_m *NSM) EXPECT() *NSM_Expecter {
	return &NSM_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type NSM
func (_mock *NSM) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// NSM_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type NSM_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *NSM_Expecter) Close() *NSM_Close_Call {
	return &NSM_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *NSM_Close_Call) Run(run func()) *NSM_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *NSM_Close_Call) Return(err error) *NSM_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *NSM_Close_Call) RunAndReturn(run func() error) *NSM_Close_Call {
	_c.Call.Return(run)
	return _c
}

// DescribePCR provides a mock function for the type NSM
func (_mock *NSM) DescribePCR(index uint16) ([]byte, bool, error) {
	ret := _mock.Called(index)

	if len(ret) == 0 {
		panic("no return value specified for DescribePCR")
	}

	var r0 []byte
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(uint16) ([]byte, bool, error)); ok {
		return returnFunc(index)
	}
	if returnFunc, ok := ret.Get(0).(func(uint16) []byte); ok {
		r0 = returnFunc(index)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint16) bool); ok {
		r1 = returnFunc(index)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(uint16) error); ok {
		r2 = returnFunc(index)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// NSM_DescribePCR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribePCR'
type NSM_DescribePCR_Call struct {
	*mock.Call
}

// DescribePCR is a helper method to define mock.On call
//   - index
func (_e *NSM_Expecter) DescribePCR(index interface{}) *NSM_DescribePCR_Call {
	return &NSM_DescribePCR_Call{Call: _e.mock.On("DescribePCR", index)}
}

func (_c *NSM_DescribePCR_Call) Run(run func(index uint16)) *NSM_DescribePCR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint16))
	})
	return _c
}

func (_c *NSM_DescribePCR_Call) Return(pcr []byte, lock bool, err error) *NSM_DescribePCR_Call {
	_c.Call.Return(pcr, lock, err)
	return _c
}

func (_c *NSM_DescribePCR_Call) RunAndReturn(run func(index uint16) ([]byte, bool, error)) *NSM_DescribePCR_Call {
	_c.Call.Return(run)
	return _c
}

// ExtendPCR provides a mock function for the type NSM
func (_mock *NSM) ExtendPCR(index uint16, data []byte) ([]byte, error) {
	ret := _mock.Called(index, data)

	if len(ret) == 0 {
		panic("no return value specified for ExtendPCR")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint16, []byte) ([]byte, error)); ok {
		return returnFunc(index, data)
	}
	if returnFunc, ok := ret.Get(0).(func(uint16, []byte) []byte); ok {
		r0 = returnFunc(index, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint16, []byte) error); ok {
		r1 = returnFunc(index, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NSM_ExtendPCR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtendPCR'
type NSM_ExtendPCR_Call struct {
	*mock.Call
}

// ExtendPCR is a helper method to define mock.On call
//   - index
//   - data
func (_e *NSM_Expecter) ExtendPCR(index interface{}, data interface{}) *NSM_ExtendPCR_Call {
	return &NSM_ExtendPCR_Call{Call: _e.mock.On("ExtendPCR", index, data)}
}

func (_c *NSM_ExtendPCR_Call) Run(run func(index uint16, data []byte)) *NSM_ExtendPCR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint16), args[1].([]byte))
	})
	return _c
}

func (_c *NSM_ExtendPCR_Call) Return(pcr []byte, err error) *NSM_ExtendPCR_Call {
	_c.Call.Return(pcr, err)
	return _c
}

func (_c *NSM_ExtendPCR_Call) RunAndReturn(run func(index uint16, data []byte) ([]byte, error)) *NSM_ExtendPCR_Call {
	_c.Call.Return(run)
	return _c
}

// GetAttestation provides a mock function for the type NSM
func (_mock *NSM) GetAttestation(nonce []byte, publicKey []byte, userData []byte) ([]byte, error) {
	ret := _mock.Called(nonce, publicKey, userData)

	if len(ret) == 0 {
		panic("no return value specified for GetAttestation")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte, []byte, []byte) ([]byte, error)); ok {
		return returnFunc(nonce, publicKey, userData)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte, []byte, []byte) []byte); ok {
		r0 = returnFunc(nonce, publicKey, userData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte, []byte, []byte) error); ok {
		r1 = returnFunc(nonce, publicKey, userData)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NSM_GetAttestation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAttestation'
type NSM_GetAttestation_Call struct {
	*mock.Call
}

// GetAttestation is a helper method to define mock.On call
//   - nonce
//   - publicKey
//   - userData
func (_e *NSM_Expecter) GetAttestation(nonce interface{}, publicKey interface{}, userData interface{}) *NSM_GetAttestation_Call {
	return &NSM_GetAttestation_Call{Call: _e.mock.On("GetAttestation", nonce, publicKey, userData)}
}

func (_c *NSM_GetAttestation_Call) Run(run func(nonce []byte, publicKey []byte, userData []byte)) *NSM_GetAttestation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].([]byte), args[2].([]byte))
	})
	return _c
}

func (_c *NSM_GetAttestation_Call) Return(attestation []byte, err error) *NSM_GetAttestation_Call {
	_c.Call.Return(attestation, err)
	return _c
}

func (_c *NSM_GetAttestation_Call) RunAndReturn(run func(nonce []byte, publicKey []byte, userData []byte) ([]byte, error)) *NSM_GetAttestation_Call {
	_c.Call.Return(run)
	return _c
}

// GetDescription provides a mock function for the type NSM
func (_mock *NSM) GetDescription() (*drivers.NSMDescription, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDescription")
	}

	var r0 *drivers.NSMDescription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*drivers.NSMDescription, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *drivers.NSMDescription); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*drivers.NSMDescription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NSM_GetDescription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDescription'
type NSM_GetDescription_Call struct {
	*mock.Call
}

// GetDescription is a helper method to define mock.On call
func (_e *NSM_Expecter) GetDescription() *NSM_GetDescription_Call {
	return &NSM_GetDescription_Call{Call: _e.mock.On("GetDescription")}
}

func (_c *NSM_GetDescription_Call) Run(run func()) *NSM_GetDescription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *NSM_GetDescription_Call) Return(description *drivers.NSMDescription, err error) *NSM_GetDescription_Call {
	_c.Call.Return(description, err)
	return _c
}

func (_c *NSM_GetDescription_Call) RunAndReturn(run func() (*drivers.NSMDescription, error)) *NSM_GetDescription_Call {
	_c.Call.Return(run)
	return _c
}

// GetRandom provides a mock function for the type NSM
func (_mock *NSM) GetRandom(length uint16) ([]byte, error) {
	ret := _mock.Called(length)

	if len(ret) == 0 {
		panic("no return value specified for GetRandom")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint16) ([]byte, error)); ok {
		return returnFunc(length)
	}
	if returnFunc, ok := ret.Get(0).(func(uint16) []byte); ok {
		r0 = returnFunc(length)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint16) error); ok {
		r1 = returnFunc(length)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NSM_GetRandom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRandom'
type NSM_GetRandom_Call struct {
	*mock.Call
}

// GetRandom is a helper method to define mock.On call
//   - length
func (_e *NSM_Expecter) GetRandom(length interface{}) *NSM_GetRandom_Call {
	return &NSM_GetRandom_Call{Call: _e.mock.On("GetRandom", length)}
}

func (_c *NSM_GetRandom_Call) Run(run func(length uint16)) *NSM_GetRandom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint16))
	})
	return _c
}

func (_c *NSM_GetRandom_Call) Return(random []byte, err error) *NSM_GetRandom_Call {
	_c.Call.Return(random, err)
	return _c
}

func (_c *NSM_GetRandom_Call) RunAndReturn(run func(length uint16) ([]byte, error)) *NSM_GetRandom_Call {
	_c.Call.Return(run)
	return _c
}

// LockPCR provides a mock function for the type NSM
func (_mock *NSM) LockPCR(index uint16) error {
	ret := _mock.Called(index)

	if len(ret) == 0 {
		panic("no return value specified for LockPCR")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint16) error); ok {
		r0 = returnFunc(index)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// NSM_LockPCR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LockPCR'
type NSM_LockPCR_Call struct {
	*mock.Call
}

// LockPCR is a helper method to define mock.On call
//   - index
func (_e *NSM_Expecter) LockPCR(index interface{}) *NSM_LockPCR_Call {
	return &NSM_LockPCR_Call{Call: _e.mock.On("LockPCR", index)}
}

func (_c *NSM_LockPCR_Call) Run(run func(index uint16)) *NSM_LockPCR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint16))
	})
	return _c
}

func (_c *NSM_LockPCR_Call) Return(err error) *NSM_LockPCR_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *NSM_LockPCR_Call) RunAndReturn(run func(index uint16) error) *NSM_LockPCR_Call {
	_c.Call.Return(run)
	return _c
}

// LockPCRs provides a mock function for the type NSM
func (_mock *NSM) LockPCRs(end uint16) error {
	ret := _mock.Called(end)

	if len(ret) == 0 {
		panic("no return value specified for LockPCRs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint16) error); ok {
		r0 = returnFunc(end)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// NSM_LockPCRs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LockPCRs'
type NSM_LockPCRs_Call struct {
	*mock.Call
}

// LockPCRs is a helper method to define mock.On call
//   - end
func (_e *NSM_Expecter) LockPCRs(end interface{}) *NSM_LockPCRs_Call {
	return &NSM_LockPCRs_Call{Call: _e.mock.On("LockPCRs", end)}
}

func (_c *NSM_LockPCRs_Call) Run(run func(end uint16)) *NSM_LockPCRs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint16))
	})
	return _c
}

func (_c *NSM_LockPCRs_Call) Return(err error) *NSM_LockPCRs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *NSM_LockPCRs_Call) RunAndReturn(run func(end uint16) error) *NSM_LockPCRs_Call {
	_c.Call.Return(run)
	return _c
}
