// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/tahardi/bearclave/internal/drivers"
)

// NewSEV creates a new instance of SEV. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSEV(t interface {
	mock.TestingT
	Cleanup(func())
}) *SEV {
	mock := &SEV{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SEV is an autogenerated mock type for the SEV type
type SEV struct {
	mock.Mock
}

type SEV_Expecter struct {
	mock *mock.Mock
}

func (_m *SEV) EXPECT() *SEV_Expecter {
	return &SEV_Expecter{mock: &_m.Mock}
}

// GetReport provides a mock function for the type SEV
func (_mock *SEV) GetReport(options ...drivers.SEVReportOption) (*drivers.SEVReportResult, error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(options)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetReport")
	}

	var r0 *drivers.SEVReportResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(...drivers.SEVReportOption) (*drivers.SEVReportResult, error)); ok {
		return returnFunc(options...)
	}
	if returnFunc, ok := ret.Get(0).(func(...drivers.SEVReportOption) *drivers.SEVReportResult); ok {
		r0 = returnFunc(options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*drivers.SEVReportResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(...drivers.SEVReportOption) error); ok {
		r1 = returnFunc(options...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SEV_GetReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReport'
type SEV_GetReport_Call struct {
	*mock.Call
}

// GetReport is a helper method to define mock.On call
//   - options
func (_e *SEV_Expecter) GetReport(options ...interface{}) *SEV_GetReport_Call {
	return &SEV_GetReport_Call{Call: _e.mock.On("GetReport",
		append([]interface{}{}, options...)...)}
}

func (_c *SEV_GetReport_Call) Run(run func(options ...drivers.SEVReportOption)) *SEV_GetReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[0].([]drivers.SEVReportOption)
		run(variadicArgs...)
	})
	return _c
}

func (_c *SEV_GetReport_Call) Return(result *drivers.SEVReportResult, err error) *SEV_GetReport_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *SEV_GetReport_Call) RunAndReturn(run func(options ...drivers.SEVReportOption) (*drivers.SEVReportResult, error)) *SEV_GetReport_Call {
	_c.Call.Return(run)
	return _c
}
