// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewTDX creates a new instance of TDX. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTDX(t interface {
	mock.TestingT
	Cleanup(func())
}) *TDX {
	mock := &TDX{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TDX is an autogenerated mock type for the TDX type
type TDX struct {
	mock.Mock
}

type TDX_Expecter struct {
	mock *mock.Mock
}

func (_m *TDX) EXPECT() *TDX_Expecter {
	return &TDX_Expecter{mock: &_m.Mock}
}

// GetReport provides a mock function for the type TDX
func (_mock *TDX) GetReport(data []byte) ([]byte, error) {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for GetReport")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) ([]byte, error)); ok {
		return returnFunc(data)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = returnFunc(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TDX_GetReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReport'
type TDX_GetReport_Call struct {
	*mock.Call
}

// GetReport is a helper method to define mock.On call
//   - data
func (_e *TDX_Expecter) GetReport(data interface{}) *TDX_GetReport_Call {
	return &TDX_GetReport_Call{Call: _e.mock.On("GetReport", data)}
}

func (_c *TDX_GetReport_Call) Run(run func(data []byte)) *TDX_GetReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *TDX_GetReport_Call) Return(report []byte, err error) *TDX_GetReport_Call {
	_c.Call.Return(report, err)
	return _c
}

func (_c *TDX_GetReport_Call) RunAndReturn(run func(data []byte) ([]byte, error)) *TDX_GetReport_Call {
	_c.Call.Return(run)
	return _c
}
