// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/tahardi/bearclave/internal/drivers/controllers"
)

// NewTSMController creates a new instance of TSMController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTSMController(t interface {
	mock.TestingT
	Cleanup(func())
}) *TSMController {
	mock := &TSMController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TSMController is an autogenerated mock type for the TSMController type
type TSMController struct {
	mock.Mock
}

type TSMController_Expecter struct {
	mock *mock.Mock
}

func (_m *TSMController) EXPECT() *TSMController_Expecter {
	return &TSMController_Expecter{mock: &_m.Mock}
}

// GetReport provides a mock function for the type TSMController
func (_mock *TSMController) GetReport(options ...controllers.TSMReportOption) (*controllers.TSMReportResult, error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(options)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetReport")
	}

	var r0 *controllers.TSMReportResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(...controllers.TSMReportOption) (*controllers.TSMReportResult, error)); ok {
		return returnFunc(options...)
	}
	if returnFunc, ok := ret.Get(0).(func(...controllers.TSMReportOption) *controllers.TSMReportResult); ok {
		r0 = returnFunc(options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*controllers.TSMReportResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(...controllers.TSMReportOption) error); ok {
		r1 = returnFunc(options...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TSMController_GetReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReport'
type TSMController_GetReport_Call struct {
	*mock.Call
}

// GetReport is a helper method to define mock.On call
//   - options
func (_e *TSMController_Expecter) GetReport(options ...interface{}) *TSMController_GetReport_Call {
	return &TSMController_GetReport_Call{Call: _e.mock.On("GetReport",
		append([]interface{}{}, options...)...)}
}

func (_c *TSMController_GetReport_Call) Run(run func(options ...controllers.TSMReportOption)) *TSMController_GetReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[0].([]controllers.TSMReportOption)
		run(variadicArgs...)
	})
	return _c
}

func (_c *TSMController_GetReport_Call) Return(tsmResult *controllers.TSMReportResult, err error) *TSMController_GetReport_Call {
	_c.Call.Return(tsmResult, err)
	return _c
}

func (_c *TSMController_GetReport_Call) RunAndReturn(run func(options ...controllers.TSMReportOption) (*controllers.TSMReportResult, error)) *TSMController_GetReport_Call {
	_c.Call.Return(run)
	return _c
}
