processes:
  enclave-server-1:
    description: The Enclave Application
    command: go run ./enclave-server-1/main.go
    ready_log_line: "Enclave server 1 started"
  enclave-server-2:
    description: The Enclave Application
    command: go run ./enclave-server-2/main.go
    ready_log_line: "Enclave server 2 started"
  enclave-proxy:
    description: The Enclave-Proxy Application
    command: go run ./enclave-proxy/main.go
    ready_log_line: "Proxy server started"
  nonclave:
    description: The Non-Enclave Application
    command: go run ./nonclave/main.go
    depends_on:
      enclave-server-1:
        condition: process_log_ready
      enclave-server-2:
        condition: process_log_ready
      enclave-proxy:
        condition: process_log_ready
    availability:
      exit_on_end: true
