platform: "notee"
attestations:
  "enclave-server":
    measurement: "Not a TEE platform. Code measurements are not real."
servers:
  "enclave-server":
    cid: 4
    port: 8082
    route: ""
proxy:
  port: 8080
