platform: "tdx"
attestations:
  "enclave-server":
    measurement: "QJwM0+Y9nqVNgXz4UZg6IgExJiZkrIzQLMai4Z/SkdL90MwDXXeJuYKkOpKkQkyZ"
servers:
  "enclave-server":
    cid: 4
    port: 8082
    route: ""
proxy:
  port: 8080
