platform: "nitro"
proxy:
  port: 8080
servers:
  "enclave-server-1":
    route: "/v1"
  "enclave-server-2":
    route: "/v2"
measurement: |
  {
    "pcrs": {
      "0": "xmoP0FwJC49s/e3zyUvSeueOws2ehWd2MJ80x+VWW/0aMky+IOxtAn2iVur8NVbl",
      "1": "S01bNmGz78EpIJAMgOEm5M54PFIt5sAqKlv3rzorkye4Z3bxiOS+HBxAShKdvaST",
      "2": "fBtbhtgIuO/uTLdxYAZTDEHuPmiRBZ4Ieq+4QEQxZ8uHe0EIqdOnvi2H953HPoNs",
      "3": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "4": "qCPabIHXU+nhGcZdNOlh6t6ts85vPpXbEhRxY1f+azLcAvahbgsBN+sKbCfnE+yq",
      "8": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    },
    "module_id": ""
  }
