platform: "nitro"
proxy:
  port: 8080
servers:
  "enclave-server-1":
    route: "/v1"
  "enclave-server-2":
    route: "/v2"
measurement: |
  {
    "pcrs": {
      "0": "7dzor27KE1kLh91poqB/VDYy9Wqp12Y8eN/V5YWjnU1takWgfM5a8UEihaubkLDS",
      "1": "S01bNmGz78EpIJAMgOEm5M54PFIt5sAqKlv3rzorkye4Z3bxiOS+HBxAShKdvaST",
      "2": "dlS6+n07wZQqw8BlJgnyRblDrk0jI+msa7V1xZHdBbcGcbkAgzRzC7akT4YEmmeb",
      "3": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "4": "qCPabIHXU+nhGcZdNOlh6t6ts85vPpXbEhRxY1f+azLcAvahbgsBN+sKbCfnE+yq",
      "8": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    },
    "module_id": ""
  }
