name: On Schedule

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  notee-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        example: [hello-world, hello-http, hello-http-multi]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'

      - name: Install Process Compose
        run: |
          sh -c "$(curl --location https://raw.githubusercontent.com/F1bonacc1/process-compose/main/scripts/get-pc.sh)" -- -d -b /usr/local/bin

      - name: Run Notee Example - ${{ matrix.example }}
        working-directory: examples/${{ matrix.example }}
        run: make

